spring.application.name=processador

# DATA SOURCE
spring.datasource.url=jdbc:postgresql://localhost:5433/pedidos_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password

# JPA/HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

rabbitmq.exchange.name=pedidos.v1.pedidod-criado
rabbitmq.queue.name=pedidos.v1.pedidos-criado.gerar-processamento